import type { KnowledgeSource } from "./types";
const source = (
  id: string,
  title: string,
  url: string,
  locator: string,
  verifiedAt = "2026-10-07",
): KnowledgeSource => ({ id, title, url, locator, verifiedAt });
export const sources = {
  men: source(
    "men",
    "MEN — technik elektryk",
    "https://infozawodowe.men.gov.pl/zawody/technik-elektryk",
    "Kwalifikacje i opis zawodu",
  ),
  curriculum: source(
    "curriculum",
    "Podstawa programowa technika elektryka",
    "https://infozawodowe.men.gov.pl/image/professionCoreCurriculum/technik-elektryk_3b7e9eb0755edb97718ea6d976c20ab9.pdf",
    "s. 3–8 i 11–15: elektrotechnika, dokumentacja, montaż i eksploatacja",
    "2026-10-08",
  ),
  cke: source(
    "cke",
    "CKE — informatory, formuła 2019",
    "https://egzaminy.gov.pl/egzamin-zawodowy/formula-2019/informatory",
    "Wykaz informatorów; mapa zakresu, bez deklaracji pełnego przygotowania",
  ),
  contactor: source(
    "contactor",
    "Schneider LC1D09P7 — karta",
    "https://iportal2.schneider-electric.com/Contents/docs/SQD-LC1D09P7.PDF",
    "s. 1–4: cewka, styki, kategoria użytkowania; weryfikacja katalogowa 2026-10-05",
    "2026-10-05",
  ),
  tesys: source(
    "tesys",
    "Schneider — instrukcja osprzętu LAD z rysunkami TeSys D",
    "https://download.se.com/files?p_Doc_Ref=0381869_01A55&p_File_Name=0381869_01A55_04.pdf&p_enDocType=Instruction+sheet",
    "Rysunki montażowe osprzętu LAD oraz przyłączy TeSys D; nie pełna karta konkretnego SKU; weryfikacja katalogowa 2026-10-05",
  ),
  coil: source(
    "coil",
    "Schneider — położenie zacisków cewki TeSys D",
    "https://www.se.com/us/en/faqs/FA110040/",
    "Control coil terminals; dotyczy rodziny TeSys D",
  ),
  auxiliary: source(
    "auxiliary",
    "Schneider — LADN11 i LADN11P",
    "https://www.se.com/pl/pl/faqs/FA400841/",
    "Oznaczenia NO i NC różnych wariantów bloku",
  ),
  button: source(
    "button",
    "Schneider XB5AA35 — karta",
    "https://iportal.se.com/Contents/docs/SQD-XB5AA35_DATASHEET.PDF",
    "s. 1–2: 1 NO + 1 NC, powrót sprężynowy; weryfikacja katalogowa 2026-10-05",
    "2026-10-05",
  ),
  mcb: source(
    "mcb",
    "Hager MBN116E",
    "https://hager.com/pl/katalog/produkt/mbn116e-mcb-6ka-1p-b-16a",
    "Dane techniczne i schemat 1–2; weryfikacja katalogowa 2026-10-02",
    "2026-10-02",
  ),
  rcd: source(
    "rcd",
    "ABB — instrukcja F200",
    "https://library.e.abb.com/public/6de074bdabef4a1eb0d5bc13e9c3903d/F200%20B%20PLUS_2013.pdf",
    "Obsługa dźwigni i TEST; odniesienie funkcjonalne, nie model SKU",
    "2026-10-03",
  ),
  bistable: source(
    "bistable",
    "F&F BIS-411 — schemat",
    "https://www.fif.com.pl/img/cms/schematy/bis/2/BIS-411-pl-schemat.jpg",
    "Schemat przyłączenia 230 V: 1, 3, 6, 10, 11, 12; katalog 2026-10-03",
    "2026-10-03",
  ),
  stairs: source(
    "stairs",
    "F&F AS-212 — instrukcja E240306",
    "https://fif.com.pl/pliki/0/746/AS-212-instructions-for-use-pl-1.pdf",
    "s. 1–4: działanie, schemat i parametry",
  ),
  timer: source(
    "timer",
    "F&F PCU-510 DUO — instrukcja E231117",
    "https://www.fif.com.pl/pl/index.php?controller=attachment&id_attachment=361",
    "s. 1–2 i 5–7: funkcje, zasilanie i dwa zestyki; katalog 2026-10-03",
    "2026-10-03",
  ),
  supply: source(
    "supply",
    "Mean Well HDR-60 — karta 2026-04-03",
    "https://www.meanwell.com/Upload/PDF/HDR-60/HDR-60-SPEC.PDF",
    "s. 2: wariant 24 V; s. 4: mechanika i zaciski",
  ),
  finder: source(
    "finder",
    "Finder — seria 40",
    "https://cdn.findernet.com/app/uploads/S40EN.pdf",
    "s. 3–4: cewki i zestyki; rysunki i podstawy w końcowej części karty; odniesienie ogólne, nie binding SKU",
  ),
  wago: source(
    "wago",
    "WAGO — złączka ochronna 283-677",
    "https://www.wago.com/gb/rail-mount-terminal-blocks/3-conductor-ground-terminal-block/p/283-677",
    "Przykład złączki ochronnej na szynę DIN; nie dowód topologii modeli edu-*",
  ),
  model: source(
    "model",
    "Pracownia — zakres modeli dydaktycznych",
    "https://github.com/Choniawko/ele/blob/main/docs/SIMULATION_SCOPE.md",
    "Profile edukacyjne, solver MNA i ograniczenia; stan repozytorium 2026-10-07",
  ),
  task101: source(
    "task101",
    "Pracownia — zweryfikowany wzorzec ELE.02-101",
    "https://github.com/Choniawko/ele/blob/main/docs/PHYSICAL_ELE02_101.md",
    "Mapa wzorca, gałęzie B6/B10, równoległe oprawy i gniazdo; adaptacja dydaktyczna odróżniona od arkusza",
    "2026-10-09",
  ),
  task108: source(
    "task108",
    "Pracownia — zweryfikowany wzorzec ELE.02-108",
    "https://github.com/Choniawko/ele/blob/main/docs/ELE02_108.md",
    "Podtrzymanie własnym NO K1, oba STOP, lewy kierunek trzymany oraz jawne założenia modelu",
    "2026-10-09",
  ),
  motor: source(
    "motor",
    "ABB — Manual for Low Voltage Motors 01-2009",
    "https://library.e.abb.com/public/70a30c0d0999feacc1257dd90035cf07/LVStdMotorsManual_EN_01_2009.pdf",
    "§3.8.1 i §3.9, s. drukowana 9; Figure 1, s. drukowana 129 (strona PDF 21): połączenia Y/Δ i zmiana kolejności faz; odniesienie ogólne, nie binding SKU",
    "2026-10-08",
  ),
  thermal: source(
    "thermal",
    "Schneider — zaciski przekaźników przeciążeniowych LRD",
    "https://www.se.com/be/en/faqs/FA107663/",
    "Resolution: NC 95–96, NO 97–98 i ich działanie po wyzwoleniu; odniesienie do TeSys D LRD, nie odbiór edu-thermal ani wyłącznika silnikowego",
    "2026-10-08",
  ),
};
