// Run only after reviewing product topology. The committed snapshot is NOT regenerated by build.
import { writeFileSync } from "node:fs";
import { availableProducts } from "@catalog/index";
import { theoryFallback } from "../packages/knowledge/bindings";
const contactMeaning: Record<string, string> = {
  manual: "zamykany operatorem",
  "manual-inverse": "NC rozwierany operatorem",
  "stop-inverse": "NC rozwierany STOP",
  mechanism: "NO zamykany mechanizmem",
  "mechanism-inverse": "NC rozwierany mechanizmem",
  healthy: "NC otwierany po wyzwoleniu",
  tripped: "NO zamykany po wyzwoleniu",
};
const snapshot = availableProducts
  .filter((p) => theoryFallback[p.behaviorId])
  .map((p) => ({
    productId: p.id,
    productRevision: p.revision,
    topologyRevision: p.topology.revision,
    articleId: theoryFallback[p.behaviorId]!,
    terminals: Object.fromEntries(
      p.topology.terminals.map((t) => [
        t.id,
        {
          sectionId: "terminals",
          explanation: `${t.label}: ${t.role}. ${p.educational ? "Mapa profilu dydaktycznego." : "Mapa konkretnego produktu w katalogu."} Funkcja w instalacji zależy od połączeń.`,
        },
      ]),
    ),
    fragments: Object.fromEntries(
      p.topology.connections.map((c) => [
        c.id,
        {
          sectionId: c.kind === "coil" ? "operation" : "reference",
          explanation: `${c.from}–${c.to}: ${c.kind === "coil" ? "cewka" : c.kind === "contact" ? `styk: ${contactMeaning[c.condition ?? ""] ?? "sprawdź opis aparatu"}` : c.kind === "bridge" ? "połączenie stałe" : c.kind === "load" ? "odbiornik / uzwojenie" : "blok elektroniki"}. ${p.educational ? "Model dydaktyczny." : "Mapa katalogowa produktu."}`,
          terminalIds: [c.from, c.to].filter((id) =>
            p.topology.terminals.some((t) => t.id === id),
          ),
        },
      ]),
    ),
  }));
writeFileSync(
  "packages/knowledge/binding-snapshot.json",
  JSON.stringify(snapshot, null, 2) + "\n",
);
